// Import required tools
import { useState, useEffect } from 'react';
import Head from 'next/head';
import { createClient } from 'next-sanity';
import imageUrlBuilder from '@sanity/image-url';

// Import Styles and fonts
import { Karla, Archivo } from '@next/font/google'
import styles from '../styles/Home.module.scss';

// Import components
import { Header, Main, Footer, Project } from "../components/index"

// Define the fonts variables as per next/font requirements
const karla = Karla({ weight: ['400', '700'], subsets: ['latin'], variable: '--karla-font' })

const archivo = Archivo({ weight: ['400', '500'], subsets: ['latin'], variable: '--archivo-font' })

export default function Home({ projects })
{

  const [expand, setExpand] = useState(false);

  const onClick = (e) =>
  {
    e.preventDefault();
    console.log('I have been clicked')
    setExpand(expand => !expand);
  }

  return (
    <>
      <Head>
        <title>Alejandra's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel=" shortcut icon" href="http://localhost:3000/favicon.ico?v=2" />
      </Head>
      <div className={archivo.variable}>
        <div className={styles.text}>
          <Header onClick={onClick} className={expand ? styles.menuExpanded : styles.menuContracted} className1={expand ? styles.menuExpanded : styles.siteBranding} className3={expand ? styles.mastHeadExpanded : styles.mastHead} />
          <Main>
            {projects.map(project => (<Project key={project._id} name={project.name} description={project.description} url={project.url} github={project.github} image={urlFor(project.image.asset).url()} />))}
          </Main>
          <Footer />
        </div>
      </div>
    </>
  )
}

const client = createClient(
  {
    projectId: 'mgub6pfu',
    dataset: 'production',
    apiVersion: '2022-01-24',
    useCdn: false
  }
);

const builder = imageUrlBuilder(client);

export const urlFor = (source) => builder.image(source);

export async function getStaticProps()
{
  const projects = await client.fetch(`*[_type == "project"]`);
  console.log(projects);
  return {
    props: {
      projects: projects
    },
  }
}
